export type AudioFeaturesObject = {
  acousticness?: number;
  analysis_url?: string;
  danceability?: number;
  duration_ms?: number;
  energy?: number;
  id?: string;
  instrumentalness?: number;
  key?: ;
  liveness?: number;
  loudness?: ;
  mode?: ;
  speechiness?: number;
  tempo?: ;
  time_signature?: ;
  track_href?: string;
  type?: string;
  uri?: string;
  valence?: number;
};