export type AudiobookBase = {
  authors: [];
  available_markets: string[];
  copyrights: [];
  description: string;
  html_description: string;
  edition?: string;
  explicit: boolean;
  external_urls: ;
  href: string;
  id: string;
  images: [];
  languages: string[];
  media_type: string;
  name: string;
  narrators: [];
  publisher: string;
  type: string;
  uri: string;
  total_chapters: number;
};