/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import type { ContextObject } from './contextObject';
import type { CurrentlyPlayingObjectItem } from './currentlyPlayingObjectItem';
import type { DisallowsObject } from './disallowsObject';

export interface CurrentlyPlayingObject {
  /** A Context Object. Can be `null`. */
  context?: ContextObject;
  /** Unix Millisecond Timestamp when data was fetched */
  timestamp?: number;
  /** Progress into the currently playing track or episode. Can be `null`. */
  progress_ms?: number;
  /** If something is currently playing, return `true`. */
  is_playing?: boolean;
  /** The currently playing track or episode. Can be `null`. */
  item?: CurrentlyPlayingObjectItem;
  /** The object type of the currently playing item. Can be one of `track`, `episode`, `ad` or `unknown`.
 */
  currently_playing_type?: string;
  /** Allows to update the user interface based on which playback actions are available within the current context.
 */
  actions?: DisallowsObject;
}
