/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import type { QueryMarketParameter } from './queryMarketParameter';
import type { QueryOffsetParameter } from './queryOffsetParameter';
import type { QueryAdditionalTypesParameter } from './queryAdditionalTypesParameter';

export type GetPlaylistsTracksParams = {
/**
 * An [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
  If a country code is specified, only content that is available in that market will be returned.<br/>
  If a valid user access token is specified in the request header, the country associated with
  the user account will take priority over this parameter.<br/>
  _**Note**: If neither market or user country are provided, the content is considered unavailable for the client._<br/>
  Users can view the country that is associated with their account in the [account settings](https://www.spotify.com/se/account/overview/).

 */
market?: QueryMarketParameter;
/**
 * Filters for the query: a comma-separated list of the
fields to return. If omitted, all fields are returned. For example, to get
just the total number of items and the request limit:<br/>`fields=total,limit`<br/>A
dot separator can be used to specify non-reoccurring fields, while parentheses
can be used to specify reoccurring fields within objects. For example, to
get just the added date and user ID of the adder:<br/>`fields=items(added_at,added_by.id)`<br/>Use
multiple parentheses to drill down into nested objects, for example:<br/>`fields=items(track(name,href,album(name,href)))`<br/>Fields
can be excluded by prefixing them with an exclamation mark, for example:<br/>`fields=items.track.album(!external_urls,images)`

 */
fields?: string;
/**
 * The maximum number of items to return. Default: 20. Minimum: 1. Maximum: 100.

 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * The index of the first item to return. Default: 0 (the first item). Use with limit to get the next set of items.

 */
offset?: QueryOffsetParameter;
/**
 * A comma-separated list of item types that your client supports besides the default `track` type. Valid types are: `track` and `episode`.<br/>
_**Note**: This parameter was introduced to allow existing clients to maintain their current behaviour and might be deprecated in the future._<br/>
In addition to providing this parameter, make sure that your client properly handles cases of new types in the future by checking against the `type` field of each object.

 */
additional_types?: QueryAdditionalTypesParameter;
};
