/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import type {
  ArrayOfBooleansResponse,
  CheckCurrentUserFollowsParams,
  CheckIfUserFollowsPlaylistParams,
  CursorPagedArtistsResponse,
  FollowArtistsUsersBody,
  FollowArtistsUsersParams,
  FollowPlaylistBody,
  ForbiddenResponse,
  GetFollowedParams,
  GetUsersTopArtistsParams,
  GetUsersTopTracksParams,
  OnePrivateUserResponse,
  OnePublicUserResponse,
  PagingArtistObjectResponse,
  PagingTrackObjectResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse,
  UnfollowArtistsUsersBody,
  UnfollowArtistsUsersParams
} from '../../model';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';



  
  
  
/**
 * Get detailed profile information about the current user (including the
current user's username).

 * @summary Get Current User's Profile

 */
export const getCurrentUsersProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OnePrivateUserResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me`,options
    );
  }



export const getGetCurrentUsersProfileKey = () => [`https://api.spotify.com/v1/me`] as const;

export type GetCurrentUsersProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUsersProfile>>>
export type GetCurrentUsersProfileQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get Current User's Profile

 */
export const useGetCurrentUsersProfile = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCurrentUsersProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCurrentUsersProfileKey() : null);
  const swrFn = () => getCurrentUsersProfile(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get public profile information about a Spotify user.

 * @summary Get User's Profile

 */
export const getUsersProfile = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OnePublicUserResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/users/${userId}`,options
    );
  }



export const getGetUsersProfileKey = (userId: string,) => [`https://api.spotify.com/v1/users/${userId}`] as const;

export type GetUsersProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersProfile>>>
export type GetUsersProfileQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get User's Profile

 */
export const useGetUsersProfile = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  userId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(userId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersProfileKey(userId) : null);
  const swrFn = () => getUsersProfile(userId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Add the current user as a follower of a playlist.

 * @summary Follow Playlist

 */
export const followPlaylist = (
    playlistId: string,
    followPlaylistBody: FollowPlaylistBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/playlists/${playlistId}/followers`,
      followPlaylistBody,options
    );
  }



export const getFollowPlaylistMutationFetcher = (playlistId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: FollowPlaylistBody }) => {
    return followPlaylist(playlistId, arg, options);
  }
}
export const getFollowPlaylistMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/followers`] as const;

export type FollowPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof followPlaylist>>>
export type FollowPlaylistMutationError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Follow Playlist

 */
export const useFollowPlaylist = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof followPlaylist>>, TError, Key, FollowPlaylistBody, Awaited<ReturnType<typeof followPlaylist>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getFollowPlaylistMutationKey(playlistId);
  const swrFn = getFollowPlaylistMutationFetcher(playlistId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove the current user as a follower of a playlist.

 * @summary Unfollow Playlist

 */
export const unfollowPlaylist = (
    playlistId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `https://api.spotify.com/v1/playlists/${playlistId}/followers`,options
    );
  }



export const getUnfollowPlaylistMutationFetcher = (playlistId: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return unfollowPlaylist(playlistId, options);
  }
}
export const getUnfollowPlaylistMutationKey = (playlistId: string,) => [`https://api.spotify.com/v1/playlists/${playlistId}/followers`] as const;

export type UnfollowPlaylistMutationResult = NonNullable<Awaited<ReturnType<typeof unfollowPlaylist>>>
export type UnfollowPlaylistMutationError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Unfollow Playlist

 */
export const useUnfollowPlaylist = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof unfollowPlaylist>>, TError, Key, Arguments, Awaited<ReturnType<typeof unfollowPlaylist>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUnfollowPlaylistMutationKey(playlistId);
  const swrFn = getUnfollowPlaylistMutationFetcher(playlistId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current user's followed artists.

 * @summary Get Followed Artists

 */
export const getFollowed = (
    params: GetFollowedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CursorPagedArtistsResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/following`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetFollowedKey = (params: GetFollowedParams,) => [`https://api.spotify.com/v1/me/following`, ...(params ? [params]: [])] as const;

export type GetFollowedQueryResult = NonNullable<Awaited<ReturnType<typeof getFollowed>>>
export type GetFollowedQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get Followed Artists

 */
export const useGetFollowed = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: GetFollowedParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFollowed>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFollowedKey(params) : null);
  const swrFn = () => getFollowed(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Add the current user as a follower of one or more artists or other Spotify users.

 * @summary Follow Artists or Users

 */
export const followArtistsUsers = (
    followArtistsUsersBody: FollowArtistsUsersBody,
    params: FollowArtistsUsersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/following`,
      followArtistsUsersBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getFollowArtistsUsersMutationFetcher = (params: FollowArtistsUsersParams, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: FollowArtistsUsersBody }) => {
    return followArtistsUsers(arg, params, options);
  }
}
export const getFollowArtistsUsersMutationKey = (params: FollowArtistsUsersParams,) => [`https://api.spotify.com/v1/me/following`, ...(params ? [params]: [])] as const;

export type FollowArtistsUsersMutationResult = NonNullable<Awaited<ReturnType<typeof followArtistsUsers>>>
export type FollowArtistsUsersMutationError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Follow Artists or Users

 */
export const useFollowArtistsUsers = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: FollowArtistsUsersParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof followArtistsUsers>>, TError, Key, FollowArtistsUsersBody, Awaited<ReturnType<typeof followArtistsUsers>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getFollowArtistsUsersMutationKey(params);
  const swrFn = getFollowArtistsUsersMutationFetcher(params, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove the current user as a follower of one or more artists or other Spotify users.

 * @summary Unfollow Artists or Users

 */
export const unfollowArtistsUsers = (
    unfollowArtistsUsersBody: UnfollowArtistsUsersBody,
    params: UnfollowArtistsUsersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `https://api.spotify.com/v1/me/following`,{data:
      unfollowArtistsUsersBody, 
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getUnfollowArtistsUsersMutationFetcher = (params: UnfollowArtistsUsersParams, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UnfollowArtistsUsersBody }) => {
    return unfollowArtistsUsers(arg, params, options);
  }
}
export const getUnfollowArtistsUsersMutationKey = (params: UnfollowArtistsUsersParams,) => [`https://api.spotify.com/v1/me/following`, ...(params ? [params]: [])] as const;

export type UnfollowArtistsUsersMutationResult = NonNullable<Awaited<ReturnType<typeof unfollowArtistsUsers>>>
export type UnfollowArtistsUsersMutationError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Unfollow Artists or Users

 */
export const useUnfollowArtistsUsers = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: UnfollowArtistsUsersParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof unfollowArtistsUsers>>, TError, Key, UnfollowArtistsUsersBody, Awaited<ReturnType<typeof unfollowArtistsUsers>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUnfollowArtistsUsersMutationKey(params);
  const swrFn = getUnfollowArtistsUsersMutationFetcher(params, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check to see if the current user is following one or more artists or other Spotify users.

 * @summary Check If User Follows Artists or Users

 */
export const checkCurrentUserFollows = (
    params: CheckCurrentUserFollowsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ArrayOfBooleansResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/following/contains`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getCheckCurrentUserFollowsKey = (params: CheckCurrentUserFollowsParams,) => [`https://api.spotify.com/v1/me/following/contains`, ...(params ? [params]: [])] as const;

export type CheckCurrentUserFollowsQueryResult = NonNullable<Awaited<ReturnType<typeof checkCurrentUserFollows>>>
export type CheckCurrentUserFollowsQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Check If User Follows Artists or Users

 */
export const useCheckCurrentUserFollows = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params: CheckCurrentUserFollowsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkCurrentUserFollows>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckCurrentUserFollowsKey(params) : null);
  const swrFn = () => checkCurrentUserFollows(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Check to see if one or more Spotify users are following a specified playlist.

 * @summary Check if Users Follow Playlist

 */
export const checkIfUserFollowsPlaylist = (
    playlistId: string,
    params: CheckIfUserFollowsPlaylistParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ArrayOfBooleansResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/playlists/${playlistId}/followers/contains`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getCheckIfUserFollowsPlaylistKey = (playlistId: string,
    params: CheckIfUserFollowsPlaylistParams,) => [`https://api.spotify.com/v1/playlists/${playlistId}/followers/contains`, ...(params ? [params]: [])] as const;

export type CheckIfUserFollowsPlaylistQueryResult = NonNullable<Awaited<ReturnType<typeof checkIfUserFollowsPlaylist>>>
export type CheckIfUserFollowsPlaylistQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Check if Users Follow Playlist

 */
export const useCheckIfUserFollowsPlaylist = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  playlistId: string,
    params: CheckIfUserFollowsPlaylistParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof checkIfUserFollowsPlaylist>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(playlistId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getCheckIfUserFollowsPlaylistKey(playlistId,params) : null);
  const swrFn = () => checkIfUserFollowsPlaylist(playlistId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current user's top artists based on calculated affinity.

 * @summary Get User's Top Artists

 */
export const getUsersTopArtists = (
    params?: GetUsersTopArtistsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagingArtistObjectResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/top/artists`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetUsersTopArtistsKey = (params?: GetUsersTopArtistsParams,) => [`https://api.spotify.com/v1/me/top/artists`, ...(params ? [params]: [])] as const;

export type GetUsersTopArtistsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersTopArtists>>>
export type GetUsersTopArtistsQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get User's Top Artists

 */
export const useGetUsersTopArtists = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersTopArtistsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersTopArtists>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersTopArtistsKey(params) : null);
  const swrFn = () => getUsersTopArtists(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get the current user's top tracks based on calculated affinity.

 * @summary Get User's Top Tracks

 */
export const getUsersTopTracks = (
    params?: GetUsersTopTracksParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PagingTrackObjectResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/top/tracks`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetUsersTopTracksKey = (params?: GetUsersTopTracksParams,) => [`https://api.spotify.com/v1/me/top/tracks`, ...(params ? [params]: [])] as const;

export type GetUsersTopTracksQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersTopTracks>>>
export type GetUsersTopTracksQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get User's Top Tracks

 */
export const useGetUsersTopTracks = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  params?: GetUsersTopTracksParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUsersTopTracks>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUsersTopTracksKey(params) : null);
  const swrFn = () => getUsersTopTracks(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
